 
export default {
  "assumptions": {
    "currency": "eur",
    "offerNames": "if name is not specified, it is auto generated by implementation",
    "rangeBoundary": "inclusive",
    "weight": "gram"
  },
  "zones": {
    "1eu": {
      "countryCodes": [
        "BE",
        "DK",
        "FR",
        "LU",
        "MC",
        "NL",
        "AT",
        "PL",
        "CZ"
      ],
      "name": "1 (EU)",
      "offers": {
        "basePrice": 13.20,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 0.90,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "1noneu": {
      "countryCodes": [
        "LI",
        "CH"
      ],
      "name": "1 (non-EU)",
      "offers": {
        "basePrice": 21.30,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 0.90,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "2eu": {
      "countryCodes": [
        "AD",
        "GB",
        "IT",
        "SM",
        "SE",
        "SK",
        "SI",
        "ES",
        "HU",
        "VA"
      ],
      "name": "2 (EU)",
      "offers": {
        "basePrice": 13.30,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 0.90,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "3eu": {
      "countryCodes": [
        "BG",
        "EE",
        "FI",
        "GR",
        "IE",
        "HR",
        "LV",
        "LT",
        "MT",
        "PT",
        "RO",
        "CY"
      ],
      "name": "3 (EU)",
      "offers": {
        "basePrice": 13.30,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 1.00,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "3noneu": {
      "countryCodes": [
        "AL",
        "BA",
        "IS",
        "MK",
        "MD",
        "ME",
        "NO",
        "RS",
        "UA",
        "BY"
      ],
      "name": "3 (non-EU)",
      "offers": {
        "basePrice": 20.30,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 1.8,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "4": {
      "countryCodes": [
        "EG",
        "DZ",
        "GE",
        "IL",
        "LB",
        "LY",
        "MA",
        "RU",
        "SY",
        "TN",
        "TR"
      ],
      "offers": {
        "basePrice": 24.55,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 2.75,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "5": {
      "countryCodes": [
        "AF",
        "AM",
        "AZ",
        "BH",
        "BD",
        "BT",
        "BN",
        "CN",
        "IN",
        "ID",
        "IQ",
        "IR",
        "JP",
        "YE",
        "JO",
        "KH",
        "CA",
        "KZ",
        "QA",
        "KG",
        "KW",
        "LA",
        "MY",
        "MV",
        "MX",
        "MN",
        "MM",
        "NP",
        "KP",
        "OM",
        "TL",
        "PK",
        "PG",
        "PH",
        "SA",
        "SG",
        "LK",
        "KR",
        "TJ",
        "TW",
        "TH",
        "TM",
        "US",
        "UZ",
        "AE",
        "VN"
      ],
      "offers": {
        "basePrice": 28.40,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 5.90,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "6": {
      "countryCodes": [
        "AO",
        "AG",
        "GQ",
        "AR",
        "ET",
        "AU",
        "BS",
        "BB",
        "BZ",
        "BJ",
        "BO",
        "BW",
        "BR",
        "BF",
        "BI",
        "CL",
        "CR",
        "CD",
        "DM",
        "DO",
        "DJ",
        "EC",
        "SV",
        "CI",
        "ER",
        "FJ",
        "GA",
        "GM",
        "GH",
        "GD",
        "GT",
        "GN",
        "GW",
        "GY",
        "HT",
        "HN",
        "JM",
        "CM",
        "CV",
        "KE",
        "KI",
        "CO",
        "KM",
        "CG",
        "CU",
        "LS",
        "LR",
        "MG",
        "MW",
        "ML",
        "MH",
        "MR",
        "MU",
        "FM",
        "MZ",
        "NA",
        "NR",
        "NZ",
        "NI",
        "NE",
        "NG",
        "PW",
        "PA",
        "PY",
        "PE",
        "RW",
        "ST",
        "SB",
        "ZM",
        "WS",
        "SN",
        "SC",
        "SL",
        "ZW",
        "SO",
        "KN",
        "LC",
        "VC",
        "ZA",
        "SD",
        "SS",
        "SR",
        "SZ",
        "TZ",
        "TG",
        "TO",
        "TT",
        "TA",
        "TD",
        "TV",
        "UG",
        "UY",
        "VU",
        "VE",
        "CF"
      ],
      "offers": {
        "basePrice": 36.0,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 7.90,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "national": {
      "countryCodes": [
        "DE"
      ],
      "offers": [
        {
          "maxWeight": 1000,
          "price": 5.05,
          "type": "package"
        },
        {
          "maxWeight": 3000,
          "price": 5.55,
          "type": "package"
        },
        {
          "maxWeight": 5000,
          "price": 6.60,
          "type": "package"
        },
        {
          "maxWeight": 10000,
          "price": 8.70,
          "type": "package"
        },
        {
          "maxWeight": 20000,
          "price": 13.60,
          "type": "package"
        },
        {
          "maxWeight": 31500,
          "price": 16.20,
          "type": "package"
        }
      ]
    }
  }
}
