/* eslint-disable */
export default {
  "assumptions": {
    "currency": "eur",
    "dimensions": {
      "xRightward": "width",
      "yUpward": "height",
      "zForward": "depth"
    },
    "length": "cm",
    "ranges": {
      "beginBoundary": "inclusive",
      "endBoundary": "inclusive"
    },
    "weight": "gram"
  },
  "zones": {
    "1": {
      "countryCodes": [
        "BE",
        "BG",
        "EE",
        "IE",
        "HR",
        "LV",
        "LT",
        "LU",
        "MT",
        "MC",
        "AT",
        "PL",
        "PT",
        "RO",
        "SE",
        "SK",
        "SI",
        "CZ",
        "HU",
        "DK",
        "FI",
        "FR",
        "GR",
        "GB",
        "IT",
        "NL",
        "ES",
        "CY"
      ],
      "name": "1 (all EU countries)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 4.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }    
        },
        {
          "maxWeight": 2000,
          "name": "Package up to 2kg",
          "price": 13.99,
          "type": "package",
          "height": 60,
          "width": 30,
          "depth": 15,
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 15.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
          "additionalRule": {
            "ruleType": "L+2xW+2xH",
            "maxTotalDimension": 300,
            "maxHeight": 120,
            "maxWidth": 60,
            "maxDepth": 60
          } 
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 20.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
          "additionalRule": {
            "ruleType": "L+2xW+2xH",
            "maxTotalDimension": 300,
            "maxHeight": 120,
            "maxWidth": 60,
            "maxDepth": 60
          } 
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 31.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 44.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "2": {
      "countryCodes": [
        "CH"
      ],
      "name": "2 (Switzerland)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 12.7,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 26.90,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 34.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 48.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 55.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "3": {
      "countryCodes": [
        "AD",
        "AL",
        "BY",
        "BA",
        "GE",
        "IS",
        "XK",
        "LI",
        "MK",
        "MD",
        "ME",
        "NO",
        "SM",
        "RS",
        "TR",
        "UA",
        "VA"
      ],
      "name": "3 (Non-EU Europe)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 15.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 29.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 37.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 52.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 60.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "4": {
      "countryCodes": [
        "RU"
      ],
      "name": "4 (Russia)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 15.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 30.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 37.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 54.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "5": {
      "countryCodes": [
        "US"
      ],
      "name": "5 (USA)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 15.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 36.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 53.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 75.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 105.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "6": {
      "countryCodes": [
        "DZ",
        "AM",
        "AZ",
        "CA",
        "EG",
        "IL",
        "JO",
        "KZ",
        "LB",
        "LY",
        "MA",
        "PS",
        "SY",
        "TN"
      ],
      "name": "6 (World)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 15.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 37.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 51.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 71.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 98.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "7": {
      "countryCodes": [
        "CN"
      ],
      "name": "7 (China)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 15.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 42.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 58.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 94.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 125.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "8": {
      "countryCodes": [
        "CC",
        "PC",
        "AF",
        "AX",
        "AS",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "AW",
        "AU",
        "BS",
        "BH",
        "BD",
        "BB",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BQ",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BF",
        "BI",
        "KH",
        "CM",
        "CV",
        "KY",
        "CF",
        "TD",
        "CL",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "CU",
        "CW",
        "DJ",
        "DM",
        "DO",
        "EC",
        "SV",
        "GQ",
        "ER",
        "ET",
        "FK",
        "FO",
        "FJ",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GH",
        "GI",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GG",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "HK",
        "IN",
        "ID",
        "IR",
        "IQ",
        "IM",
        "JM",
        "JP",
        "JE",
        "KE",
        "KI",
        "KP",
        "KR",
        "KW",
        "KG",
        "LA",
        "LS",
        "LR",
        "MO",
        "MG",
        "MW",
        "MY",
        "MV",
        "ML",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "MX",
        "FM",
        "MN",
        "MS",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NC",
        "NZ",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "MP",
        "OM",
        "PK",
        "PW",
        "PA",
        "PG",
        "PY",
        "PE",
        "PH",
        "PN",
        "PR",
        "QA",
        "RE",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "ST",
        "SA",
        "SN",
        "SC",
        "SL",
        "SG",
        "SX",
        "SB",
        "SO",
        "ZA",
        "GS",
        "SS",
        "LK",
        "SD",
        "SR",
        "SJ",
        "SZ",
        "TW",
        "TJ",
        "TZ",
        "TH",
        "TL",
        "TG",
        "TK",
        "TO",
        "TT",
        "TM",
        "TC",
        "TV",
        "UG",
        "AE",
        "UM",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "YE",
        "ZM",
        "ZW"
      ],
      "name": "8 (World)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel XS up to 2kg",
          "price": 8.89,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 3
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 15.89,
          "type": "parcel",
          "height": 60,
          "width": 20,
          "depth": 10,
          "additionalRule": {
            "ruleType": "L+W+H",
            "maxTotalDimension": 90,
            "maxSide": 60
          }  
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 45.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 61.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "Package up to 20kg",
          "price": 100.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 131.99,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "national": {
      "countryCodes": [
        "DE"
      ],
      "name": "National (Germany)",
      "offers": [
        {
          "maxWeight": 2000,
          "name": "Parcel S up to 2kg",
          "price": 3.79,
          "type": "parcel",
          "height": 35,
          "width": 25,
          "depth": 10
        },
        {
          "maxWeight": 2000,
          "name": "Parcel M up to 2kg",
          "price": 4.49,
          "type": "parcel",
          "height": 60,
          "width": 30,
          "depth": 15,
        },
        {
          "maxWeight": 2000,
          "name": "Package up to 2kg",
          "price": 5.49,
          "type": "package",
          "height": 60,
          "width": 30,
          "depth": 15,
        },
        {
          "maxWeight": 5000,
          "name": "Package up to 5kg",
          "price": 6.49,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
          "additionalRule": {
            "ruleType": "L+2xW+2xH",
            "maxTotalDimension": 300,
            "maxHeight": 120,
            "maxWidth": 60,
            "maxDepth": 60
          }
        },
        {
          "maxWeight": 10000,
          "name": "Package up to 10kg",
          "price": 9.49,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
          "additionalRule": {
            "ruleType": "L+2xW+2xH",
            "maxTotalDimension": 300,
            "maxHeight": 120,
            "maxWidth": 60,
            "maxDepth": 60
          }
        },
        {
          "maxWeight": 31500,
          "name": "Package up to 31.5kg",
          "price": 17.49,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    }
  }
};
