/* eslint-disable */
export default {
  "assumptions": {
    "currency": "eur",
    "offerNames": "if name is not specified, it is auto generated by implementation",
    "rangeBoundary": "inclusive",
    "weight": "gram"
  },
  "zones": {
    "1eu": {
      "countryCodes": [
        "BE",
        "DK",
        "FR",
        "LU",
        "MC",
        "NL",
        "AT",
        "PL",
        "CZ"
      ],
      "name": "1 (EU)",
      "offers": {
        "basePrice": 10.6,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 0.85,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "1noneu": {
      "countryCodes": [
        "LI",
        "CH"
      ],
      "name": "1 (non-EU)",
      "offers": {
        "basePrice": 13.25,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 1.5,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "2eu": {
      "countryCodes": [
        "AD",
        "GB",
        "IT",
        "SM",
        "SE",
        "SK",
        "SI",
        "ES",
        "HU",
        "VA"
      ],
      "name": "2 (EU)",
      "offers": {
        "basePrice": 11.35,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 0.95,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "3eu": {
      "countryCodes": [
        "BG",
        "EE",
        "FI",
        "GR",
        "IE",
        "HR",
        "LV",
        "LT",
        "MT",
        "PT",
        "RO",
        "CY"
      ],
      "name": "3 (EU)",
      "offers": {
        "basePrice": 11.45,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 1.05,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "3noneu": {
      "countryCodes": [
        "AL",
        "BA",
        "IS",
        "MK",
        "MD",
        "ME",
        "NO",
        "RS",
        "UA",
        "BY"
      ],
      "name": "3 (non-EU)",
      "offers": {
        "basePrice": 14.2,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 1.5,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "4": {
      "countryCodes": [
        "EG",
        "DZ",
        "GE",
        "IL",
        "LB",
        "LY",
        "MA",
        "RU",
        "SY",
        "TN",
        "TR"
      ],
      "offers": {
        "basePrice": 22.95,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 2.9,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "5": {
      "countryCodes": [
        "AF",
        "AM",
        "AZ",
        "BH",
        "BD",
        "BT",
        "BN",
        "CN",
        "IN",
        "ID",
        "IQ",
        "IR",
        "JP",
        "YE",
        "JO",
        "KH",
        "CA",
        "KZ",
        "QA",
        "KG",
        "KW",
        "LA",
        "MY",
        "MV",
        "MX",
        "MN",
        "MM",
        "NP",
        "KP",
        "OM",
        "TL",
        "PK",
        "PG",
        "PH",
        "SA",
        "SG",
        "LK",
        "KR",
        "TJ",
        "TW",
        "TH",
        "TM",
        "US",
        "UZ",
        "AE",
        "VN"
      ],
      "offers": {
        "basePrice": 23.35,
        "maxWeight": 31500,
        "roundingPrice": "ROUND_UP",
        "stepPrice": 5.2,
        "stepWeight": 1000,
        "type": "package"
      }
    },
    "6": {
      "countryCodes": [
        "AO",
        "AG",
        "GQ",
        "AR",
        "ET",
        "AU",
        "BS",
        "BB",
        "BZ",
        "BJ",
        "BO",
        "BW",
        "BR",
        "BF",
        "BI",
        "CL",
        "CR",
        "CD",
        "DM",
        "DO",
        "DJ",
        "EC",
        "SV",
        "CI",
        "ER",
        "FJ",
        "GA",
        "GM",
        "GH",
        "GD",
        "GT",
        "GN",
        "GW",
        "GY",
        "HT",
        "HN",
        "JM",
        "CM",
        "CV",
        "KE",
        "KI",
        "CO",
        "KM",
        "CG",
        "CU",
        "LS",
        "LR",
        "MG",
        "MW",
        "ML",
        "MH",
        "MR",
        "MU",
        "FM",
        "MZ",
        "NA",
        "NR",
        "NZ",
        "NI",
        "NE",
        "NG",
        "PW",
        "PA",
        "PY",
        "PE",
        "RW",
        "ST",
        "SB",
        "ZM",
        "WS",
        "SN",
        "SC",
        "SL",
        "ZW",
        "SO",
        "KN",
        "LC",
        "VC",
        "ZA",
        "SD",
        "SS",
        "SR",
        "SZ",
        "TZ",
        "TG",
        "TO",
        "TT",
        "TA",
        "TD",
        "TV",
        "UG",
        "UY",
        "VU",
        "VE",
        "CF"
      ],
      "offers": [
        {
          "maxWeight": 1000,
          "price": 32.05,
          "type": "package"
        },
        {
          "maxWeight": 2000,
          "price": 35.3,
          "type": "package"
        },
        {
          "maxWeight": 3000,
          "price": 38.55,
          "type": "package"
        },
        {
          "maxWeight": 4000,
          "price": 41.8,
          "type": "package"
        },
        {
          "maxWeight": 5000,
          "price": 45.05,
          "type": "package"
        },
        {
          "maxWeight": 6000,
          "price": 48.3,
          "type": "package"
        },
        {
          "maxWeight": 7000,
          "price": 51.55,
          "type": "package"
        },
        {
          "maxWeight": 8000,
          "price": 54.8,
          "type": "package"
        },
        {
          "maxWeight": 9000,
          "price": 58.05,
          "type": "package"
        },
        {
          "maxWeight": 10000,
          "price": 61.3,
          "type": "package"
        },
        {
          "maxWeight": 11000,
          "price": 64.55,
          "type": "package"
        },
        {
          "maxWeight": 12000,
          "price": 67.8,
          "type": "package"
        },
        {
          "maxWeight": 13000,
          "price": 71.05,
          "type": "package"
        },
        {
          "maxWeight": 14000,
          "price": 74.3,
          "type": "package"
        },
        {
          "maxWeight": 15000,
          "price": 77.55,
          "type": "package"
        },
        {
          "maxWeight": 16000,
          "price": 80.8,
          "type": "package"
        },
        {
          "maxWeight": 17000,
          "price": 84.05,
          "type": "package"
        },
        {
          "maxWeight": 18000,
          "price": 87.3,
          "type": "package"
        },
        {
          "maxWeight": 19000,
          "price": 90.55,
          "type": "package"
        },
        {
          "maxWeight": 20000,
          "price": 93.8,
          "type": "package"
        },
        {
          "maxWeight": 21000,
          "price": 97.05,
          "type": "package"
        },
        {
          "maxWeight": 22000,
          "price": 100.3,
          "type": "package"
        },
        {
          "maxWeight": 23000,
          "price": 103.55,
          "type": "package"
        },
        {
          "maxWeight": 24000,
          "price": 106.8,
          "type": "package"
        },
        {
          "maxWeight": 25000,
          "price": 110.05,
          "type": "package"
        },
        {
          "maxWeight": 26000,
          "price": 113.3,
          "type": "package"
        },
        {
          "maxWeight": 27000,
          "price": 116.55,
          "type": "package"
        },
        {
          "maxWeight": 28000,
          "price": 119.8,
          "type": "package"
        },
        {
          "maxWeight": 29000,
          "price": 123.05,
          "type": "package"
        },
        {
          "maxWeight": 30000,
          "price": 126.3,
          "type": "package"
        },
        {
          "maxWeight": 31000,
          "price": 129.56,
          "type": "package"
        },
        {
          "maxWeight": 31500,
          "price": 131.18,
          "type": "package"
        }
      ]
    },
    "national": {
      "countryCodes": [
        "DE"
      ],
      "offers": [
        {
          "maxWeight": 1000,
          "price": 4.15,
          "type": "package"
        },
        {
          "maxWeight": 3000,
          "price": 4.7,
          "type": "package"
        },
        {
          "maxWeight": 5000,
          "price": 5.75,
          "type": "package"
        },
        {
          "maxWeight": 10000,
          "price": 6.9,
          "type": "package"
        },
        {
          "maxWeight": 20000,
          "price": 9.3,
          "type": "package"
        },
        {
          "maxWeight": 31500,
          "price": 11.4,
          "type": "package"
        }
      ]
    }
  }
}
