/* eslint-disable */
export default {
  "assumptions": {
    "currency": "eur",
    "dimensions": {
      "xRightward": "width",
      "yUpward": "height",
      "zForward": "depth"
    },
    "length": "cm",
    "ranges": {
      "beginBoundary": "inclusive",
      "endBoundary": "inclusive"
    },
    "weight": "gram"
  },
  "zones": {
    "1": {
      "countryCodes": [
        "BE",
        "LU",
        "NL"
      ],
      "name": "Zone 1 - EU",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 44,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 49.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 56,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 66.10,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 83.80,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 121.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 175.70,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "2": {
      "countryCodes": [
        "AT",
        "DK",
        "FR",
        "MC"
      ],
      "name": "Zone 2 - EU",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 47.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 53,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 59.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 73.80,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 101.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 144.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 217.40,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "3": {
      "countryCodes": [
        "CZ",
        "GB",
        "IT",
        "PL",
        "ES"
      ],
      "name": "Zone 3 - EU",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 52.80,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 60.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 69.10,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 88.90,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 127.40,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 181.90,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 253.70,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "4": {
      "countryCodes": [
        "BG",
        "HR",
        "CY",
        "EE",
        "FI",
        "GR",
        "HU",
        "IE",
        "LV",
        "LT",
        "MT",
        "PT",
        "RO",
        "SK",
        "SI",
        "SE"  
      ],
      "name": "Zone 4 - EU",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 54.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 63,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 73.90,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 102.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 151.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 220.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 308.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "5": {
      "countryCodes": [
        "AD",
        "IC",
        "FO",
        "GI",
        "GG",
        "IS",
        "JE",
        "LI",
        "NO",
        "SM",
        "CH"   
      ],
      "name": "Zone 5 - Worldwide",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 44.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 51.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 60.80,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 85,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 125.80,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 183.80,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 258,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "6": {
      "countryCodes": [
        "AL",
        "BY",
        "BA",
        "XK",
        "MK",
        "MD",
        "ME",
        "RU",
        "RS",
        "TR",
        "UA",
      ],
      "name": "Zone 6 - Worldwide",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 54.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 62.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 72.40,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 112.10,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 165.40,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 241.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 350.10,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "7": {
      "countryCodes": [
        "CA",
        "MX",
        "US"
      ],
      "name": "Zone 7 - Worldwide",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 41.70,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 48.90,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 57.40,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 94.40,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 139.70,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 206,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 300.70,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "8": {
      "countryCodes": [
        "CN",
        "HK",
        "JP",
        "SG",
        "LK",
        "TW",
        "TH"
      ],
      "name": "Zone 8 - Worldwide",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 53.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 70.70,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 90,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 159.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 260.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 380.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 515.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "9": {
      "countryCodes": [
        "AU",
        "BH",
        "TL",
        "TP",
        "EG",
        "ID",
        "IL",
        "KR",
        "KW",
        "MY",
        "AN",
        "AW",
        "CW",
        "SX",
        "BQ",
        "NZ",
        "OM",
        "PH",
        "QA",
        "SA",
        "ZA",
        "AE",
        "YE"
      ],
      "name": "Zone 9 - Worldwide",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 56.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 76.10,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 98.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 183.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 308.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 452.60,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 605.10,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "10": {
      "countryCodes": [
        "PC",
        "AF",
        "AX",
        "AS",
        "AO",
        "AI",
        "AQ",
        "AG",
        "AR",
        "BS",
        "BD",
        "BB",
        "BZ",
        "BJ",
        "BM",
        "BT",
        "BO",
        "BW",
        "BV",
        "BR",
        "IO",
        "BN",
        "BF",
        "BI",
        "KH",
        "CM",
        "CV",
        "KY",
        "CF",
        "TD",
        "CL",
        "CX",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CK",
        "CR",
        "CI",
        "CU",
        "DJ",
        "DM",
        "DO",
        "EC",
        "SV",
        "GQ",
        "ER",
        "ET",
        "FK",
        "FJ",
        "GF",
        "PF",
        "TF",
        "GA",
        "GM",
        "GH",
        "GL",
        "GD",
        "GP",
        "GU",
        "GT",
        "GN",
        "GW",
        "GY",
        "HT",
        "HM",
        "HN",
        "IN",
        "IR",
        "IQ",
        "IM",
        "JM",
        "KE",
        "KI",
        "KP",
        "KG",
        "LA",
        "LS",
        "LR",
        "MO",
        "MG",
        "MW",
        "MV",
        "ML",
        "MH",
        "MQ",
        "MR",
        "MU",
        "YT",
        "FM",
        "MN",
        "MS",
        "MZ",
        "MM",
        "NA",
        "NR",
        "NP",
        "NC",
        "NI",
        "NE",
        "NG",
        "NU",
        "NF",
        "MP",
        "PK",
        "PW",
        "PA",
        "PG",
        "PY",
        "PE",
        "PN",
        "PR",
        "RE",
        "RW",
        "BL",
        "SH",
        "KN",
        "LC",
        "MF",
        "PM",
        "VC",
        "WS",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "SO",
        "GS",
        "SS",
        "SD",
        "SR",
        "SJ",
        "SZ",
        "TJ",
        "TZ",
        "TG",
        "TK",
        "TO",
        "TT",
        "TM",
        "TC",
        "TV",
        "UG",
        "UM",
        "UY",
        "UZ",
        "VU",
        "VE",
        "VN",
        "VG",
        "VI",
        "WF",
        "EH",
        "ZM",
        "ZW"
      ],
      "name": "Zone 10 - Worldwide",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 69.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 1000,
          "name": "up to 1 kg",
          "price": 92,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60, 
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 121.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 224.50,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 385.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 569.20,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 742.30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    },
    "national": {
      "countryCodes": [
        "DE"
      ],
      "name": "National (Germany)",
      "offers": [
        {
          "maxWeight":500,
          "name": "up to 0.5 kg",
          "price": 11,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60
        },
        {
          "maxWeight": 2000,
          "name": "up to 2 kg",
          "price": 14,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 5000,
          "name": "up to 5 kg",
          "price": 15,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60 
        },
        {
          "maxWeight": 10000,
          "name": "up to 10kg",
          "price": 25,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 20000,
          "name": "up to 20kg",
          "price": 30,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        },
        {
          "maxWeight": 31500,
          "name": "up to 31.5kg",
          "price": 45,
          "type": "package",
          "height": 120,
          "width": 60,
          "depth": 60,
        }
      ]
    }
  }
};
