name: build-test-service-config

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/service-config/**'
      - '.github/workflows/build-test-service-config.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/service-config/**'
      - '.github/workflows/build-test-service-config.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: service-config

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: service-config
      system: true
