name: build-test-grpc-client

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/grpc-client/**'
      - '.github/workflows/build-test-grpc-client.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/grpc-client/**'
      - '.github/workflows/build-test-grpc-client.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: grpc-client

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: grpc-client
      system: true
