name: build-test-protos

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/protos/**'
      - '.github/workflows/build-test-protos.yaml'
      - '.github/workflows/base-build-job.yaml'
  pull_request:
    paths:
      - 'packages/protos/**'
      - '.github/workflows/build-test-protos.yaml'
      - '.github/workflows/base-build-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: protos
