name: build-test-cart

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/cart/**'
      - '.github/workflows/build-test-cart.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/cart/**'
      - '.github/workflows/build-test-cart.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: cart

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: cart
      system: true
