name: build-test-gql-bot

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/gql-bot/**'
      - '.github/workflows/build-test-gql-bot.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/gql-bot/**'
      - '.github/workflows/build-test-gql-bot.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: gql-bot

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: gql-bot
      coveralls: true
