name: build-test-kafka-client

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/kafka-client/**'
      - '.github/workflows/build-test-kafka-client.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/kafka-client/**'
      - '.github/workflows/build-test-kafka-client.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: kafka-client

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: kafka-client
      coveralls: true
      system: true
      backing-only: true
