name: build-test-oidc-id-srv-integration

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/oidc-id-srv-integration/**'
      - '.github/workflows/build-test-oidc-srv-integration.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/oidc-id-srv-integration/**'
      - '.github/workflows/build-test-oidc-srv-integration.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: oidc-id-srv-integration

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: oidc-id-srv-integration
