name: build-test-logger

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/logger/**'
      - '.github/workflows/build-test-logger.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/logger/**'
      - '.github/workflows/build-test-logger.yaml'
      - '.github/workflows/base-build-job.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  build:
    uses: ./.github/workflows/base-build-job.yaml
    with:
      package: logger

  test:
    needs: build
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: logger
      system: true
      backing-only: true
      curl-elastic: true
