name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.17'
          fetch-depth: 0

      - name: Upgrade npm
        run: npm i -g npm

      - name: Install Dependencies
        run: npm ci

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-1-nx-${{ inputs.package }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            cache-1-nx-${{ inputs.package }}-${{ hashFiles('package-lock.json') }}-

      - name: Build
        run: npm run build -- -p="@restorecommerce/${{ inputs.package }}"

      - name: Version
        run: npx lerna version

      - name: Release
        run: npx lerna publish from-package --verify-access --no-private
