name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18.17'

      - name: Upgrade npm
        run: npm i -g npm

      - name: Install Dependencies
        run: npm ci

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-1-nx-${{ inputs.package }}-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            cache-1-nx-${{ inputs.package }}-${{ hashFiles('package-lock.json') }}-

      - name: Git Config
        run: |
          git config --global user.email "bot@restorecommerce.io"
          git config --global user.name "Restorecommerce Bot"

      - name: Build
        run: npm run build -- -p="@restorecommerce/${{ inputs.package }}"

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish --verify-access --no-private --conventional-commits --yes

      - name: Sync next branch
        run: |
          git checkout next
          git merge master
          git push -u origin next
