name: test-cluster-service

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'packages/cluster-service/**'
      - '.github/workflows/test-cluster-service.yaml'
      - '.github/workflows/base-test-job.yaml'
  pull_request:
    paths:
      - 'packages/cluster-service/**'
      - '.github/workflows/test-cluster-service.yaml'
      - '.github/workflows/base-test-job.yaml'

jobs:
  test:
    uses: ./.github/workflows/base-test-job.yaml
    with:
      package: cluster-service
      coveralls: true
